


/* houses */

position: absolute;
width: 525px;
height: 694px;
left: 554px;
top: 131px;



/* house2 */

position: absolute;
width: 31px;
height: 24px;
left: 554px;
top: 538px;

background: #000000;


/* house3 */

position: absolute;
width: 31px;
height: 24px;
left: 593px;
top: 339px;

background: #000000;


/* house4 */

position: absolute;
width: 31px;
height: 24px;
left: 636px;
top: 171px;

background: #000000;


/* house5 */

position: absolute;
width: 31px;
height: 24px;
left: 827px;
top: 131px;

background: #000000;


/* house6 */

position: absolute;
width: 31px;
height: 24px;
left: 1023px;
top: 197px;

background: #000000;


/* house7 */

position: absolute;
width: 31px;
height: 24px;
left: 1045px;
top: 360px;

background: #000000;


/* house8 */

position: absolute;
width: 31px;
height: 24px;
left: 1048px;
top: 568px;

background: #000000;


/* house1 */

position: absolute;
width: 31px;
height: 24px;
left: 688px;
top: 801px;

background: #000000;


/* house9 */

position: absolute;
width: 31px;
height: 24px;
left: 953px;
top: 772px;

background: #000000;


/* resources */

position: absolute;
width: 678px;
height: 822px;
left: 504px;
top: 90px;



/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 1054px;
top: 230px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 989px;
top: 200px;

background: #44FF00;


/* market */

position: absolute;
width: 9px;
height: 9px;
left: 753px;
top: 375px;

background: #FF0000;


/* water */

position: absolute;
width: 9px;
height: 9px;
left: 854px;
top: 592px;

background: #68A7FF;


/* honey */

position: absolute;
width: 9px;
height: 9px;
left: 811px;
top: 704px;

background: #FFD500;


/* honey */

position: absolute;
width: 9px;
height: 9px;
left: 965px;
top: 298px;

background: #FFD500;


/* honey */

position: absolute;
width: 9px;
height: 9px;
left: 683px;
top: 640px;

background: #FFD500;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 696px;
top: 845px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 751px;
top: 804px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 909px;
top: 812px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 742px;
top: 649px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 979px;
top: 817px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 1007px;
top: 557px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 1067px;
top: 399px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 1052px;
top: 899px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 771px;
top: 903px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 549px;
top: 747px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 536px;
top: 713px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 504px;
top: 375px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 563px;
top: 406px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 531px;
top: 390px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 734px;
top: 90px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 952px;
top: 116px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 880px;
top: 228px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 989px;
top: 494px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 1133px;
top: 838px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 1173px;
top: 371px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 1005px;
top: 366px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 890px;
top: 496px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 927px;
top: 453px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 916px;
top: 390px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 850px;
top: 509px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 775px;
top: 498px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 730px;
top: 453px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 725px;
top: 406px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 1091px;
top: 592px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 600px;
top: 527px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 658px;
top: 351px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 696px;
top: 186px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 567px;
top: 577px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 589px;
top: 370px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 620px;
top: 196px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 880px;
top: 143px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 871px;
top: 171px;

background: #44FF00;


/* smoke stack */

position: absolute;
width: 546px;
height: 686px;
left: 550px;
top: 45px;



/* smoke */

position: absolute;
width: 9px;
height: 9px;
left: 692px;
top: 678px;

background: #000000;


/* smoke */

position: absolute;
width: 9px;
height: 9px;
left: 1031px;
top: 722px;

background: #000000;


/* smoke */

position: absolute;
width: 9px;
height: 9px;
left: 770px;
top: 45px;

background: #000000;


/* smoke */

position: absolute;
width: 9px;
height: 9px;
left: 550px;
top: 249px;

background: #000000;


/* smoke */

position: absolute;
width: 9px;
height: 9px;
left: 1087px;
top: 111px;

background: #000000;
